services:
  batch:
    build:
      context: ..
      dockerfile: .devcontainer/dockerfile
    image: batch
    container_name: batch_container
    tty: true
    volumes:
      - ..:/workspace
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16.3
    container_name: db_container
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-container
    # volumes:
    #   - ".docker/mysql:/home"
    ports:
      - 5432:5432
    volumes: # 名前付きボリュームの割り当て定義を追加
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local